# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the base branch
on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check env
      run: composer check
    - name: Install dependencies
      run: composer install
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    
    ## 测试 创建数据库、运行数据库变更、运行单元测试
    - name: create db
      run: php bin/console doctrine:database:create
    - name: run db migrations
      run: php bin/console doctrine:migrations:migrate
    - name: Run test suite
      run: ./bin/phpunit
    - name: show router
      run: php bin/console debug:router


