name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v2
    - name: install swoole
      run: mkdir -p ~/build && \
        cd ~/build && \
        rm -rf ./swoole-src && \
        curl -o ./tmp/swoole.tar.gz https://github.com/swoole/swoole-src/archive/master.tar.gz -L && \
        tar zxvf ./tmp/swoole.tar.gz && \
        mv swoole-src* swoole-src && \
        cd swoole-src && \
        phpize && \
        ./configure \
        --enable-openssl \
        --enable-http2 && \
        make && sudo make install;
    - name: check env
      run: composer check;
    - name: Install dependencies
      run: composer install
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    
    ## 测试 创建数据库、运行数据库变更、运行单元测试
    - name: create db
      run: php bin/console doctrine:database:create
    - name: run db migrations
      run: php bin/console doctrine:migrations:migrate
    - name: Run test suite
      run: ./bin/phpunit

